import 'package:encarta_data/encarta_data.dart';

/// One ranked search result row (title from FTS, snippet generated by us).
class SearchResultItem {
  final int refid;
  final String title;
  final String snippet;
  final String tierBadge;
  final MediaItem? thumb;
  final bool selected;

  const SearchResultItem({
    required this.refid,
    required this.title,
    required this.snippet,
    required this.tierBadge,
    required this.thumb,
    this.selected = false,
  });

  SearchResultItem copyWith({bool? selected}) => SearchResultItem(
        refid: refid,
        title: title,
        snippet: snippet,
        tierBadge: tierBadge,
        thumb: thumb,
        selected: selected ?? this.selected,
      );
}

/// Immutable bundle for the search screen.
class SearchViewData {
  final String query;
  final List<SearchResultItem> results;
  final int offset;
  final bool hasMore;

  const SearchViewData({
    required this.query,
    required this.results,
    required this.offset,
    required this.hasMore,
  });
}
