import 'package:encarta_data/encarta_data.dart';
import 'package:encarta_render/encarta_render.dart';
import 'package:flutter/material.dart';

import '../article/article_view.dart';
import 'search_result_tile.dart';

/// One ranked search result row (title from FTS, snippet generated by us).
class SearchResultItem {
  final int refid;
  final String title;
  final String snippet;
  final String tierBadge;
  final MediaItem? thumb;
  final bool selected;

  const SearchResultItem({
    required this.refid,
    required this.title,
    required this.snippet,
    required this.tierBadge,
    required this.thumb,
    this.selected = false,
  });

  SearchResultItem copyWith({bool? selected}) => SearchResultItem(
        refid: refid,
        title: title,
        snippet: snippet,
        tierBadge: tierBadge,
        thumb: thumb,
        selected: selected ?? this.selected,
      );
}

/// Immutable bundle for the search screen.
class SearchViewData {
  final String query;
  final List<SearchResultItem> results;
  final int offset;
  final bool hasMore;

  const SearchViewData({
    required this.query,
    required this.results,
    required this.offset,
    required this.hasMore,
  });
}

/// Two-column search screen: LEFT = ranked result list, RIGHT = live preview.
class SearchView extends StatelessWidget {
  final SearchViewData data;
  final ArticleViewData? preview;
  final EncartaTheme? theme;
  final AssetResolver? assetResolver;
  final XrefTap? onXrefTap;
  final TitleForRefid? titleForRefid;
  final void Function(int refid) onSelect;
  final VoidCallback? onNextPage;

  const SearchView({
    super.key,
    required this.data,
    required this.preview,
    required this.onSelect,
    this.theme,
    this.assetResolver,
    this.onXrefTap,
    this.titleForRefid,
    this.onNextPage,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        SizedBox(
          width: 420,
          child: ListView(
            children: [
              for (final r in data.results)
                SearchResultTile(item: r, onTap: () => onSelect(r.refid)),
              if (data.hasMore && onNextPage != null)
                Padding(
                  padding: const EdgeInsets.all(12),
                  child: OutlinedButton(
                    onPressed: onNextPage,
                    child: const Text('More results'),
                  ),
                ),
            ],
          ),
        ),
        const VerticalDivider(width: 1),
        Expanded(
          child: preview == null || theme == null
              ? const Center(child: Text('Select a result to preview'))
              : Padding(
                  padding: const EdgeInsets.all(16),
                  child: EncartaArticleBody(
                    doc: preview!.doc,
                    theme: theme!,
                    assetResolver: assetResolver ?? (_, __) => const SizedBox(),
                    onXrefTap: onXrefTap ?? (_, {paraId}) {},
                    titleForRefid: titleForRefid ?? (_) => null,
                  ),
                ),
        ),
      ],
    );
  }
}
